# Generated by Django 5.2 on 2025-07-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservicehousekeepingrequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='roomservicehousekeepingrequest',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomservicelaundryrequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='roomservicelaundryrequest',
            name='room',
        ),
        migrations.DeleteModel(
            name='RoomServiceCafeRequest',
        ),
        migrations.DeleteModel(
            name='RoomServiceHousekeepingRequest',
        ),
        migrations.DeleteModel(
            name='RoomServiceLaundryRequest',
        ),
    ]
