# Generated by Django 5.2 on 2025-05-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservicecaferequest',
            name='reservation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomservicehousekeepingrequest',
            name='reservation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomservicelaundryrequest',
            name='reservation',
            field=models.CharField(max_length=100),
        ),
    ]
