# Generated by Django 5.2.4 on 2025-09-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminNew', '0002_speechactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitychoice',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_choices', to='adminNew.activity'),
        ),
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField(default=1)),
                ('scenario', models.TextField(blank=True)),
                ('timer_seconds', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminNew.activity')),
            ],
            options={
                'ordering': ['item_number'],
                'unique_together': {('activity', 'item_number')},
            },
        ),
        migrations.AddField(
            model_name='activitychoice',
            name='activity_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='adminNew.activityitem'),
        ),
    ]
