# Generated by Django 5.2.4 on 2025-09-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminNew', '0003_alter_activitychoice_activity_activityitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechactivity',
            name='reference_text',
            field=models.TextField(blank=True, help_text='Reference text for accuracy comparison'),
        ),
    ]
