# Generated by Django 5.2 on 2025-04-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('personnel', 'Personnel'), ('admin', 'Admin'), ('manager', 'Manager'), ('supervisor_laundry', 'Supervisor - Laundry'), ('supervisor_concierge', 'Supervisor - Concierge'), ('supervisor_cafe', 'Supervisor - Cafe'), ('supervisor_restaurant', 'Supervisor - Restaurant'), ('supervisor_room_service', 'Supervisor - Room Service'), ('supervisor_fnb', 'Supervisor - Food and Beverages'), ('staff_laundry', 'Staff - Laundry'), ('staff_concierge', 'Staff - Concierge'), ('staff_cafe', 'Staff - Cafe'), ('staff_restaurant', 'Staff - Restaurant'), ('staff_room_service', 'Staff - Room Service'), ('staff_fnb', 'Staff - Food and Beverages')], default='personnel', max_length=30),
        ),
    ]
