# Generated by Django 5.2 on 2025-05-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('personnel', 'Personnel'), ('admin', 'Admin'), ('manager', 'Manager'), ('supervisor_laundry', 'Supervisor - Laundry'), ('supervisor_concierge', 'Supervisor - Concierge'), ('supervisor_cafe', 'Supervisor - Cafe'), ('staff_laundry', 'Staff - Laundry'), ('staff_concierge', 'Staff - Concierge'), ('staff_cafe', 'Staff - Cafe'), ('staff_room_service', 'Staff - Room Service')], default='personnel', max_length=30),
        ),
    ]
