# Generated by Django 5.2.4 on 2025-09-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_course_customuser_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_initial',
            field=models.CharField(blank=True, help_text='Middle initial', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, help_text='Student section (e.g., 3A, 2B)', max_length=50, null=True),
        ),
    ]
