# Generated by Django 5.2 on 2025-05-13 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_reservation_delete_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(help_text="e.g. 'Wash & Fold', 'Dry Cleaning'", max_length=50)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, help_text='If billed by the hour', max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='If billed by weight (kg)', max_digits=6, null=True)),
                ('item_type', models.CharField(help_text="e.g. 'Shirts', 'Bedsheets', 'Socks'", max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Number of items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Add-ons, special requests, etc.')),
                ('payment_method', models.CharField(choices=[('CASH', 'Pay Cash'), ('ROOM', 'Charge to Room')], default='CASH', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_orders', to='staff.room')),
            ],
        ),
    ]
