# Generated by Django 5.2 on 2025-07-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='laundryorder',
            name='room',
        ),
        migrations.DeleteModel(
            name='LaundryItem',
        ),
        migrations.DeleteModel(
            name='LaundryOrder',
        ),
    ]
