# Generated by Django 5.2 on 2025-05-13 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
        ('staff', '0003_reservation_delete_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(editable=False, help_text='Auto-generated as YYYYMMDD-#####', max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('WASH_FOLD', 'Wash and Fold'), ('DRY_CLEAN', 'Dry Cleaning'), ('IRON_ONLY', 'Iron Only')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='staff.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receipt_no'], name='laundry_ord_receipt_292d6a_idx'), models.Index(fields=['status'], name='laundry_ord_status_0dd2ef_idx')],
            },
        ),
    ]
