# Generated by Django 5.2 on 2025-07-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laundry', '0002_remove_laundryorder_customer_and_more'),
        ('staff', '0008_alter_guest_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=50)),
                ('no_of_bags', models.PositiveIntegerField(default=1)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('room', 'Charge to Room')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.guest')),
            ],
        ),
    ]
