# Generated by Django 5.2 on 2025-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrytransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('room', 'Charge to Room')], max_length=255),
        ),
    ]
