# Generated by Django 5.2.4 on 2025-08-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0005_laundrytransaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundrytransaction',
            name='status',
        ),
    ]
