# Generated by Django 5.2.4 on 2025-08-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_remove_laundrytransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrytransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
