# Generated by Django 5.2.4 on 2025-09-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mcqattempt',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mcqattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcqattempt',
            name='participant_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mcqattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcqattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20),
        ),
    ]
