# Generated by custom edit for adding McqAnswer model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_mcqattempt_attempt_number_and_more'),
        ('adminNew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McqAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.mcqattempt')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminNew.activitychoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='mcqanswer',
            index=models.Index(fields=['attempt'], name='assessment_attempt_idx'),
        ),
    ]

# Generated by Django 5.2.4 on 2025-09-02 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminNew', '0001_initial'),
        ('assessment', '0002_mcqattempt_attempt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='McqAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.mcqattempt')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminNew.activitychoice')),
            ],
            options={
                'indexes': [models.Index(fields=['attempt'], name='assessment__attempt_5d5a55_idx')],
            },
        ),
    ]
