# Generated by Django 5.2.4 on 2025-09-04 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminNew', '0003_alter_activitychoice_activity_activityitem_and_more'),
        ('assessment', '0003_mcqanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqanswer',
            name='activity_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminNew.activityitem'),
        ),
        migrations.AddField(
            model_name='mcqattempt',
            name='current_item_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='mcqanswer',
            index=models.Index(fields=['attempt', 'activity_item'], name='assessment__attempt_5c10b4_idx'),
        ),
    ]
