# Generated by Django 5.2.4 on 2025-09-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_mcqanswer_activity_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqattempt',
            name='passed',
            field=models.BooleanField(default=False, help_text='Whether the attempt passed the passing threshold'),
        ),
    ]
