# Generated by Django 5.2.4 on 2025-09-08 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminNew', '0003_alter_activitychoice_activity_activityitem_and_more'),
        ('assessment', '0005_mcqattempt_passed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_info', models.CharField(max_length=255)),
                ('participant_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False, help_text='Whether the attempt passed the passing threshold')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_attempts', to='adminNew.speechactivity')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_text', models.TextField()),
                ('accuracy_score', models.FloatField(blank=True, help_text='Accuracy score based on comparison with reference text', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.speechattempt')),
            ],
            options={
                'indexes': [models.Index(fields=['attempt'], name='assessment__attempt_e8356d_idx')],
            },
        ),
    ]
