# Generated by Django 5.2 on 2025-05-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scenario', models.TextField()),
                ('timer', models.CharField(blank=True, max_length=20)),
                ('choice1', models.CharField(max_length=255)),
                ('choice2', models.CharField(max_length=255)),
                ('choice3', models.CharField(max_length=255)),
                ('choice4', models.CharField(max_length=255)),
                ('action_block', models.BooleanField(default=False)),
                ('action_reserve', models.BooleanField(default=False)),
                ('action_cash_payment', models.BooleanField(default=False)),
                ('action_customization', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechToTextActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('audio_file', models.FileField(upload_to='speech_to_text/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
