# Generated by Django 5.2 on 2025-05-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('presidential', 'Presidential Suite')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning')], default='available', max_length=20)),
                ('floor', models.IntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_zipCode', models.CharField(max_length=20)),
                ('customer_dateOfBirth', models.DateField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('number_of_guests', models.PositiveSmallIntegerField()),
                ('special_requests', models.TextField(blank=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('total_nights', models.PositiveIntegerField(editable=False)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('credit_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_card_expiry', models.DateField(blank=True, null=True)),
                ('cvc_code', models.CharField(blank=True, max_length=3, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='staff.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
