# Generated by Django 5.2 on 2025-07-05 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_remove_orderitem_menu_item_remove_order_cashier_and_more'),
        ('concierge', '0002_remove_conciergerequestspa_assigned_to_and_more'),
        ('laundry', '0002_remove_laundryorder_customer_and_more'),
        ('room_service', '0002_remove_roomservicehousekeepingrequest_customer_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('room_type', models.CharField(max_length=50)),
                ('total_of_guests', models.PositiveIntegerField()),
                ('num_of_adults', models.PositiveIntegerField()),
                ('num_of_children', models.PositiveIntegerField(default=0)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', 'Card Payment'), ('cash', 'Cash')], max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('exp_date', models.CharField(blank=True, max_length=5, null=True)),
                ('cvc_code', models.CharField(blank=True, max_length=4, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
