# Generated by Django 5.2 on 2025-05-13 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_zipCode', models.CharField(max_length=20)),
                ('customer_dateOfBirth', models.DateField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('room_type', models.CharField(max_length=100)),
                ('number_of_guests', models.PositiveSmallIntegerField()),
                ('special_requests', models.TextField(blank=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('payment_method', models.CharField(max_length=100)),
                ('credit_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_card_expiry', models.DateField(blank=True, null=True)),
                ('cvc_code', models.CharField(blank=True, max_length=3, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Checkin',
        ),
    ]
