# Generated by Django 5.2 on 2025-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_guest_booking_payment_delete_reservation_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='exp_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
