# Generated by Django 5.2 on 2025-07-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_payment_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='mobile_no',
        ),
    ]
