# Generated by Django 5.2 on 2025-07-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_guest_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_type',
            new_name='room',
        ),
    ]
