# Generated by Django 5.2 on 2025-07-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_rename_room_type_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Checked-in', 'Checked-in'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
