# Generated by Django 5.2 on 2025-07-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='billing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
