# Generated by Django 5.2 on 2025-07-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_guest_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='billing',
            field=models.TextField(blank=True, default='0', null=True),
        ),
    ]
