# Generated by Django 5.2 on 2025-07-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_guest_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='laundry_billing',
            field=models.TextField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='room_service_billing',
            field=models.TextField(blank=True, default='0', null=True),
        ),
    ]
