# Generated by Django 5.2 on 2025-07-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_guest_laundry_billing_guest_room_service_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_children_below_7',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
