# Generated by Django 5.2 on 2025-07-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_booking_no_of_children_below_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='cafe_billing',
            field=models.TextField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='excess_pax_billing',
            field=models.TextField(blank=True, default='0', null=True),
        ),
    ]
