# Generated by Django 5.2 on 2025-07-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_guest_cafe_billing_guest_excess_pax_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='additional_charge_billing',
            field=models.TextField(blank=True, default='0', null=True),
        ),
    ]
