# Generated by Django 5.2 on 2025-07-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_guest_additional_charge_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='room_service_billing',
            field=models.TextField(blank=True, default='1000', null=True),
        ),
    ]
