# Generated by Django 5.2 on 2025-07-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_guest_room_service_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='billing',
            field=models.TextField(blank=True, default='1000', null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room_service_billing',
            field=models.TextField(blank=True, default='0', null=True),
        ),
    ]
