# Generated by Django 5.2.4 on 2025-08-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_payment_total_balance'),
    ]

    operations = [
    ]
