# Generated by Django 5.2 on 2025-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_add_room_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.CharField(max_length=50, default=''),
            preserve_default=False,
        ),
    ]
