# Generated by Django 5.2.4 on 2025-08-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_fix_booking_room_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room',
            new_name='rooms',
        ),
    ]
