# Generated by Django 5.2.4 on 2025-08-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_rename_room_booking_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rooms',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
