# Generated by Django 5.2.4 on 2025-10-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_remove_booking_rooms_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
