# Generated by Django 5.2.4 on 2025-10-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_update_room_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('walkin', 'Walk-in'), ('reservation', 'Reservation'), ('checkin', 'Check-in')], default='reservation', max_length=20),
        ),
    ]
