# Generated by Django 5.2.4 on 2025-11-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_booking_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Checked-in', 'Checked-in'), ('Checked-out', 'Checked-out'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
