# Generated by Django 5.2 on 2025-05-15 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_reservation_delete_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeRequestBookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('coffee', 'Coffee'), ('snack', 'Snack'), ('meal', 'Meal')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_request_book_reservation', to='staff.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_request_book_reservation', to='staff.room')),
            ],
        ),
        migrations.CreateModel(
            name='ConciergeRequestBookSpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('towel_replacement', 'Towel Replacement'), ('linen_change', 'Linen Change'), ('amenities', 'Amenities Restock')], max_length=30)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_request_book_spa', to='staff.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_request_book_spa', to='staff.room')),
            ],
        ),
        migrations.CreateModel(
            name='ConciergeRequestTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('wash', 'Wash'), ('wash_fold', 'Wash and Fold')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_request_tour', to='staff.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_request_tour', to='staff.room')),
            ],
        ),
    ]
