# Generated by Django 5.2 on 2025-05-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0001_initial'),
        ('staff', '0003_reservation_delete_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conciergerequestbookspa',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='conciergerequestbookspa',
            name='room',
        ),
        migrations.AlterField(
            model_name='conciergerequesttour',
            name='reservation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conciergerequesttour',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_requests_tour', to='staff.room'),
        ),
        migrations.CreateModel(
            name='ConciergeRequestCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('reservation', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('coffee', 'Coffee'), ('snack', 'Snack'), ('meal', 'Meal')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_requests_cafe', to='staff.room')),
            ],
        ),
        migrations.CreateModel(
            name='ConciergeRequestSpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('reservation', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('towel_replacement', 'Towel Replacement'), ('linen_change', 'Linen Change'), ('amenities', 'Amenities Restock')], max_length=30)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_spa_requests', to='staff.room')),
            ],
        ),
        migrations.DeleteModel(
            name='ConciergeRequestBookReservation',
        ),
        migrations.DeleteModel(
            name='ConciergeRequestBookSpa',
        ),
    ]
