# Generated by Django 5.2 on 2025-05-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_role',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_role',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
