# Generated by Django 5.2.4 on 2025-11-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_service',
            field=models.CharField(blank=True, help_text="Service/app context where message was sent from (e.g., 'Room Service', 'Cafe')", max_length=30),
        ),
    ]
