# Generated by Django 5.2 on 2025-05-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_receiver_role_message_sender_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
