# Generated by Django 5.2 on 2025-05-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_receiver_remove_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
