# Generated by Django 5.2.4 on 2025-08-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ffsdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('billing', models.TextField(blank=True, default='1000', null=True)),
                ('room_service_billing', models.TextField(blank=True, default='0', null=True)),
                ('laundry_billing', models.TextField(blank=True, default='0', null=True)),
                ('cafe_billing', models.TextField(blank=True, default='0', null=True)),
                ('excess_pax_billing', models.TextField(blank=True, default='0', null=True)),
                ('additional_charge_billing', models.TextField(blank=True, default='0', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
 