# Generated by Django 5.2.4 on 2025-08-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeeping',
            name='request_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
