# Generated by Django 5.2.4 on 2025-08-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0002_housekeeping_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeeping',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
