# Generated by Django 5.2 on 2025-07-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=80)),
                ('item_category', models.CharField(max_length=70)),
                ('item_price', models.CharField(max_length=70)),
            ],
        ),
    ]
