# Generated by Django 5.2.4 on 2025-08-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_cafecategory_cafeitem_cafeorder_cafeorderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('room', 'Charge to Room')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cafeorder',
            name='service_type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('take_out', 'Take Out')], max_length=100),
        ),
    ]
