# Generated by Django 5.2 on 2025-05-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_menuitem_preparation_time_order_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Order Status History'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='preparation_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_ready_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_prepared',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='prepared_at',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
