# Generated by Django 5.2.4 on 2025-08-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_cafeorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeorder',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cafeorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash Cash Payment'), ('room', 'Charge to Room'), ('card', 'Card Payment')], max_length=100),
        ),
    ]
