# Generated by Django 5.2.4 on 2025-09-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_cafeorder_card_number_alter_cafeorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeorder',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('done', 'Done')], default='queued', max_length=20),
        ),
    ]
