# Generated by Django 5.2.4 on 2025-09-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_cafeorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeorder',
            name='cash_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cafeorder',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
